site_name: Digital Twin Education
repo_url: https://github.com/DigitalTwin-Geohub/DigitalTwinEducation
repo_name: Digital Twin Education - University of Twente

nav:
  - Home: index.md
  - Preparation for Course: Preparation.md
  - Modules:
    - Module I: Modules/Module I.md
    - Module II: Modules/Module II.md
    - Module III: Modules/Module III.md
    - Module IV: Modules/Module IV.md
    # - Module V: Modules/Module V.md
  - Assignments: 
    
    - Assingment 1: Assignment/Assignment I.md
    # - Assingment 2: Assignment/Assignment II.md
    # - Assingment 3: Assignment/Assignment III.md
    # - Assingment 4: Assignment/Assignment IV.md
    - Final Assignment: Assignment/FINAL Assignment.md
  - About:
    - License: license.md
    - Citing: citing.md



theme:
  name: material
  logo: images/6Logo Simplified500px.png
  favicon: images/6Logo Simplified100px.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: indigowhere py
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.tracking

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
  - blog:
      blog_dir: articles
      categories_url_format: "{slug}"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg